1009 ability to click on the affected urls of a pattern and see which urls have been affected
NASA-IMPACT/sde-indexing-helper pull request #1038
Opened 2024-09-26 00:36 UTC by Kirandawadi

2024-09-26 18:14 UTC, code-geek requested changes
Mostly good. I have a few comments. Lmk when you push changes and I can take a look again. Thanks!

2024-09-26 18:14 UTC, code-geek commented on sde_collections/views.py
> +        return queryset
Please create a base class-based view and inherit from it to create multiple views instead of using these if conditions in a single view.

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/css/affected_urls.css
> +
This file needs linting. VS Code should come with a default linter for CSS files. Maybe you can run "Format files" with Ctrl+Shift+P

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/css/affected_urls.css
These are a lot of additional CSS rules on top of existing ones. Are these all required/used?

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/js/affected_urls.js
> +  })
File needs linting. Please use VS Code's "Format files" feature.

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/js/affected_urls.js
> +  })
You might consider enabling "Format files on save"

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/js/affected_urls.js
> +    const i = this.querySelector('i');
Think this deserves a more descriptive variable name? I'm not sure what `i` is from querySelector.

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/js/candidate_url_list.js
>        },
Let's fix the formatting on these lines

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/js/candidate_url_list.js
>        },
Same comment for all the other `render`s we have.

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/static/js/candidate_url_list.js
> +    console.log(matchPatternId);
Do we need all these `console.log` statements in production? If not, consider removing them.

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/templates/sde_collections/affected_urls.html
> +                    </th> -->
Let's get rid of commented out code if we don't need it.

2024-09-26 18:14 UTC, code-geek commented on sde_indexing_helper/templates/sde_collections/affected_urls.html
> +                        </td> -->
Do we need these? If not, let's remove them.

2024-09-27 01:06 UTC, Kirandawadi commented on sde_collections/views.py
> +        return queryset
created base-class view which will be inherited by multiple views.

2024-09-27 01:07 UTC, Kirandawadi commented on sde_indexing_helper/static/css/affected_urls.css
> +
solved formatting issue.

2024-09-27 01:07 UTC, Kirandawadi commented on sde_indexing_helper/static/css/affected_urls.css
Refactored the affected_urls.css to only use required CSS declarations.

2024-09-27 01:08 UTC, Kirandawadi commented on sde_indexing_helper/static/js/affected_urls.js
> +  })
Solved formatting issue.

2024-09-27 01:11 UTC, Kirandawadi commented on sde_indexing_helper/static/js/affected_urls.js
> +    const i = this.querySelector('i');
This function is part of the "Include/Exclude URL" feature on the "Affected URLs" page. Currently, the basic version of the "Affected URLs" page has been pushed, which does not incorporate this feature yet. I will address this in my next commit.

2024-09-27 01:11 UTC, Kirandawadi commented on sde_indexing_helper/static/js/candidate_url_list.js
>        },
Solved the formatting issue.

2024-09-27 01:12 UTC, Kirandawadi commented on sde_indexing_helper/static/js/candidate_url_list.js
> +    console.log(matchPatternId);
Removed the debugging lines.

2024-09-27 01:12 UTC, Kirandawadi commented on sde_indexing_helper/templates/sde_collections/affected_urls.html
> +                    </th> -->
Removed the unnecessary comments block.

2024-09-27 01:12 UTC, Kirandawadi commented on sde_indexing_helper/templates/sde_collections/affected_urls.html
> +                        </td> -->
Removed the unnecessary comments block.

2025-03-20 18:47 UTC, closed without merging

2025-03-20 18:47 UTC, Kirandawadi commented
This PR is addressed by https://github.com/NASA-IMPACT/COSMOS/pull/1241